---
- name: remove httpd
  hosts: localhost
  tasks:
    - name: remove file
      file:
        path: /var/www/html/index.html
        state: absent

    - name: remove package
      package:
        name: httpd
        state: absent
